### PR TITLE
add flags when configuring the flex compilation

### PR DESCRIPTION
**Pull request by did**

### CODE REVIEW

**Comment by did** [comment]
I'm sorry, I've created my PR too soon :-( I'm just testing it right now.

**Comment by did** [comment]
alright, no more segmentation fault with this PR.

**Comment by MattFenelon** [comment]
Hi @did. Thanks for the PR. Could you give some detail on what the CFLAGS do?

**Comment by did** [comment]
you're welcome. No idea about what the CFLAGS do exactly :-) 
People here https://github.com/westes/flex/issues/442 just told that it fixed the segmentation fault issue.

**Comment by MattFenelon** [comment]
Fair enough! The flags look fairly innocuous so I'm merging this now. Thanks.

**Pull request merged**
